language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
    - pip install .

before_script:
    - cd server && pip install -r requires.txt && nohup python index.py > /dev/null
    - sleep 3

script:
    - py.test 

