language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

install:
    - pip install pytest
    - pip install pytest-cov
    - pip install codecov
    - pip install .

before_script:
    - cd server && pip install -r requires.txt && nohup python index.py > /dev/null 2>&1 &
    - sleep 3

script:
    - py.test tests --cov=$(cd tests&&python -c "import flask_restaction;print(flask_restaction.__path__[0])")

after_success:
    - codecov